name: Deploy Frontend to EC2

on:
  push:
    branches: [main] # o master, según tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_MP_PUBLIC_KEY: ${{ secrets.MP_PUBLIC_KEY }}
          VITE_MP_CLIENT_ID: ${{ secrets.MP_CLIENT_ID }}
          VITE_MP_REDIRECT_URI: ${{ secrets.MP_REDIRECT_URI }}

      - name: Create deployment package
        run: |
          cd dist
          tar -czf ../frontend-dist.tar.gz .
          cd ..

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'frontend-dist.tar.gz'
          target: '/home/ec2-user/'

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/CicloMart_front
            # Backup
            if [ -d "dist" ]; then
              mv dist dist.backup.$(date +%Y%m%d_%H%M%S)
            fi
            # Extraer
            mkdir -p dist
            cd dist
            tar -xzf /home/ec2-user/frontend-dist.tar.gz
            cd ..
            # Limpiar
            rm /home/ec2-user/frontend-dist.tar.gz
            # Reiniciar PM2
            pm2 restart ciclomart-frontend || pm2 start ecosystem.config.cjs --env production
            # Limpiar backups antiguos
            ls -t | grep "dist.backup" | tail -n +4 | xargs -r rm -rf
